### ISSUE TITLE
Add feature

### ISSUE THREAD

**Issue by nevgin** [ahmed-lotfy/loki-logback-appender#2]
Hi!
Do not consider it arrogance, but I would like to see support for multi labels. 
And less priority is the ability to specify a string pattern.
I apologize for the possibly inaccurate translation.

**Comment by ahmed-lotfy** [comment]
I can add support for multi labels soon. please open another issue for string pattern as currently i don't have enough time to work on it.

**Comment by nevgin** [comment]
ok, Thanks

**Comment by ahmed-lotfy** [comment]
Hi, I added multi-label support in version `1.0` please check new configurations in the `README` file

**Comment by nevgin** [comment]
Thanks!
