### ISSUE TITLE
Cutting fields in message  

### ISSUE THREAD

**Issue by nevgin** [ahmed-lotfy/loki-logback-appender#5]
Hi!

Help please.
Appender cutting fields in message...

Log in stdout: 2020-04-24 17:44:33.415  INFO 13430 --- [           main] r.m.p.s.metrics.impl.MetricServiceStub   : Received messages from start parser: 8

Log in Loki: 2020-04-24 17:44:33
2020-04-24 17:44:33.415 INFO ru.mts.parser.service.metrics.impl.MetricServiceStub [main] Received messages from start parser: {}

**Comment by ahmed-lotfy** [comment]
yea, i see the problem that i'm not injecting the formatted message when pushing to Loki. i pushed the fix to the same version `1.0` so please remove cached jar on your side and re-download it once more.

Thanks for reporting that !

**Comment by nevgin** [comment]
Thanks!
