### ISSUE TITLE
Connection to Loki goes through a proxy

### ISSUE THREAD

**Issue by nevgin** [ahmed-lotfy/loki-logback-appender#6]
I am run java with system variables -Dhttp.proxyHost= -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts=
Connection to Loki goes through a proxy. Although I specify out an exception...

**Comment by nevgin** [comment]
My mistake...

**Comment by ahmed-lotfy** [comment]
Hi, i was busy yesterday and didn't get a chance to respond to this one. glad you managed to fix it.
